"""MkDocs build hooks: the year, stamped where it belongs.

Generates the PDF's running header and names the PDF itself, both from
extra.dates.year and the handbook's name, so the year lives in exactly one place
in mkdocs.yml. Nothing here is specific to one handbook - see handbook.py.
Wired up via `hooks:` in mkdocs.yml.
"""

from mkdocs.structure.files import File

from .handbook import Handbook

CSS_PATH = "css/header.css"

HEADER_CSS = """\
/* Generated by hooks.py from extra.dates.year — do not edit by hand. */
@page {{
    @top-left {{
        content: '{header}';
        font-size: 10px;
        text-transform: uppercase;
    }}
}}
"""


def on_config(config):
    """Link the generated stylesheet, and name the PDF for this edition."""
    if CSS_PATH not in config.extra_css:
        config.extra_css.append(CSS_PATH)

    # Hooks' on_config runs after the plugins', so this wins over any output_path
    # set in mkdocs.yml - one less place for the year to go stale. The plugin
    # reads the value at on_post_build, well after this.
    to_pdf = config.plugins.get("to-pdf")
    if to_pdf is not None:
        to_pdf.config["output_path"] = f"{Handbook(config).file_base}.pdf"
    return config


def on_files(files, config):
    """Create css/header.css in memory, stamped with this edition's name."""
    book = Handbook(config)
    header = f"{book.year} {book.title}".replace("'", "\\'")
    files.append(
        File.generated(config, CSS_PATH, content=HEADER_CSS.format(header=header))
    )
    return files
